{% set version = "2.13.0" %}

package:
  name: fontconfig
  version: {{ version }}

source:
  url: http://www.freedesktop.org/software/fontconfig/release/fontconfig-{{ version }}.tar.bz2
  sha256: 91dde8492155b7f34bb95079e79be92f1df353fcc682c19be90762fd3e12eeb9
  patches:
    # Apply upstream patch to ensure macOS's UUID is used.
    # ref: https://bugs.freedesktop.org/show_bug.cgi?id=105366
    - bug_105366.patch
    # This patch won't be submitted upstream. It's use here is to ensure the prefix used
    # to refer to the `fonts.conf` file.
    - fcf.patch       # [linux]

build:
  number: 2
  skip: True                       # [win]
  binary_has_prefix_files:         # [linux]
    - lib/libfontconfig.so.1.11.1  # [linux]

requirements:
  build:
    - {{ compiler("c") }}
    - pkg-config
    - gperf
    - automake
    - libtool

  host:
    - freetype
    - libiconv
    - libpng
    - libxml2
    - icu      # [not win]
    - libuuid  # [linux]

  run:
    - freetype
    - libiconv
    - libpng
    - libxml2
    - icu      # [not win]
    - libuuid  # [linux]

test:
  commands:
    # Test CLI.
    - fc-cache --help
    - fc-cat --help
    - fc-list --help
    - fc-match --help
    - fc-pattern --help
    - fc-query --help
    - fc-scan --help
    - fc-validate --help

    # Test for libraries.
    - test -f "${PREFIX}/lib/libfontconfig.a"
    - test -f "${PREFIX}/lib/libfontconfig.dylib"  # [osx]
    - test -f "${PREFIX}/lib/libfontconfig.so"     # [linux]

about:
  home: http://www.freedesktop.org/wiki/Software/fontconfig/
  license: MIT
  license_file: COPYING
  summary: 'A library for configuring and customizing font access.'

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
