travis:
  secure:
    BINSTAR_TOKEN: RBSbwiHDXAIALGb8j/ZouIcRrnLIYaxI2FyyWKOsT6BXH4MseS12Z80rsFHgCB15OsvBcQHzaGnHbxoHPBBwsfDcicbonDd8MLA/cc3rgMqmaG4HNSKo4nv7ZZtwg7s8Slx4qGtmNjdgPIEEMV5TwGIjJOC+Dd7qhelATd2LAha0KHEV1BIAQp4PkJLH4pv9nB/wcuTGoHE+Su2e9TpGATwpzhsO1WjaBW4ZJA+6oMUaTe6oNSp7vWgXKiKQNNrdrqSGl3SIoEk++XPvAelPK6gfSvP83QnsMv0Nvn2fu9ENO95jk6nkTcDbeNGCMZtdOvBbEU3RfTrdzypQbBzcDBTIGOF4axGTpKRAb88Fe3HAk6beJkXCPXzBKymdWxXBDGLTgtvy69xsU5wcgYOEWq9eL/xO+Mt/k0Rb0fwAk4jv0G0vyBEHRYtozIJBpYUBVafuDyVtg/F48F7le7HToZA5cKvErrScLMh/GJnb38z+6lVAOiLDWEOm5P6uFt6vmzkxMDBZMVgEO61eC879rdCI4S52PwihKFKX0GM3z7AyguCCyUBRix+/yofgdLCfhCUMPODpJhNa/0dfmJh/Md1R/KnT9+1898+prP+qLV8OliBQjw92W3S9EqLm+n2utBdX4HeNbwWpRCKe3IPzJnp8pKuuahBUVrnz8TqVD1A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
